import { theme, type ThemeConfig } from 'antd'
import {
  BRAND_PRIMARY,
  BRAND_PRIMARY_HOVER,
  COLOR_BG,
  COLOR_BORDER,
  COLOR_TEXT,
  COLOR_TEXT_SECONDARY,
} from '../constants'

export const antdTheme: ThemeConfig = {
  cssVar: { key: 'ot' },
  hashed: false,
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: BRAND_PRIMARY,
    colorPrimaryHover: BRAND_PRIMARY_HOVER,
    colorPrimaryActive: '#1739C7',
    colorPrimaryBg: '#EEF2FF',
    colorPrimaryBgHover: '#E0E7FF',
    colorPrimaryBorder: '#C7D2FE',
    colorPrimaryText: BRAND_PRIMARY,

    colorText: COLOR_TEXT,
    colorTextSecondary: COLOR_TEXT_SECONDARY,
    colorTextTertiary: '#94A3B8',
    colorTextQuaternary: '#CBD5E1',

    colorBgBase: '#FFFFFF',
    colorBgLayout: COLOR_BG,
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgSpotlight: '#F1F5F9',

    colorBorder: COLOR_BORDER,
    colorBorderSecondary: '#F1F5F9',

    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    borderRadiusXS: 4,

    fontFamily:
      "system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'PingFang SC', 'Microsoft YaHei', sans-serif",
    fontFamilyCode:
      "ui-monospace, SFMono-Regular, 'JetBrains Mono', Menlo, Consolas, monospace",
    fontSize: 14,
    fontSizeSM: 13,
    fontSizeLG: 16,
    fontSizeXL: 18,
    fontSizeHeading1: 30,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 17,
    fontSizeHeading5: 15,

    lineHeight: 1.6,
    lineHeightHeading1: 1.35,
    lineHeightHeading2: 1.4,

    controlHeight: 36,
    controlHeightSM: 30,
    controlHeightLG: 42,

    motionDurationFast: '0.1s',
    motionDurationMid: '0.16s',
    motionDurationSlow: '0.24s',
    motionEaseOut: 'cubic-bezier(0.16, 1, 0.3, 1)',
    motionEaseInOut: 'cubic-bezier(0.65, 0, 0.35, 1)',

    boxShadow:
      '0 1px 2px 0 rgba(15, 23, 42, 0.04), 0 1px 3px 0 rgba(15, 23, 42, 0.06)',
    boxShadowSecondary:
      '0 4px 16px -4px rgba(15, 23, 42, 0.08), 0 2px 6px -2px rgba(15, 23, 42, 0.04)',
    boxShadowTertiary:
      '0 20px 60px -12px rgba(15, 23, 42, 0.18), 0 8px 24px -8px rgba(15, 23, 42, 0.08)',

    wireframe: false,
    padding: 16,
    paddingLG: 24,
    paddingSM: 12,
    paddingXS: 8,
    paddingXXS: 4,
  },
  components: {
    Layout: {
      headerBg: '#FFFFFF',
      headerHeight: 60,
      headerPadding: '0 24px',
      bodyBg: '#F7F8FA',
      siderBg: '#FFFFFF',
      triggerBg: 'transparent',
      triggerColor: '#475569',
      footerBg: 'transparent',
      footerPadding: '24px 32px',
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: '#EEF2FF',
      itemSelectedColor: BRAND_PRIMARY,
      itemHoverBg: '#F1F5F9',
      itemHoverColor: COLOR_TEXT,
      itemBorderRadius: 8,
      itemMarginInline: 8,
      itemPaddingInline: 12,
      itemHeight: 40,
      iconSize: 16,
      iconMarginInlineEnd: 10,
      collapsedIconSize: 18,
      groupTitleColor: '#94A3B8',
      groupTitleFontSize: 12,
      darkItemBg: 'transparent',
      subMenuItemBg: 'transparent',
    },
    Card: {
      headerBg: 'transparent',
      headerHeight: 56,
      headerHeightSM: 48,
      paddingLG: 24,
      borderRadiusLG: 12,
    },
    Button: {
      borderRadius: 8,
      controlHeight: 36,
      controlHeightSM: 30,
      controlHeightLG: 42,
      paddingContentHorizontal: 16,
      paddingContentHorizontalSM: 12,
      paddingContentHorizontalLG: 20,
      defaultBorderColor: COLOR_BORDER,
      defaultColor: COLOR_TEXT,
      defaultBg: '#FFFFFF',
      defaultHoverBorderColor: '#CBD5E1',
      defaultHoverBg: '#F8FAFC',
      defaultHoverColor: COLOR_TEXT,
      primaryShadow: '0 1px 2px rgba(45, 91, 255, 0.16)',
    },
    Input: {
      borderRadius: 8,
      controlHeight: 36,
      controlHeightSM: 30,
      controlHeightLG: 42,
      paddingBlock: 8,
      paddingInline: 12,
      activeBorderColor: BRAND_PRIMARY,
      hoverBorderColor: '#CBD5E1',
      activeShadow: '0 0 0 3px rgba(45, 91, 255, 0.12)',
    },
    Select: {
      borderRadius: 8,
      controlHeight: 36,
      optionSelectedBg: '#EEF2FF',
      optionSelectedColor: BRAND_PRIMARY,
    },
    DatePicker: {
      borderRadius: 8,
      controlHeight: 36,
    },
    Modal: {
      borderRadiusLG: 12,
      paddingContentHorizontalLG: 28,
      titleFontSize: 17,
      titleLineHeight: 1.5,
    },
    Table: {
      borderRadius: 8,
      headerBg: '#F8FAFC',
      headerColor: COLOR_TEXT_SECONDARY,
      headerSplitColor: 'transparent',
      headerBorderRadius: 8,
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
      cellFontSize: 14,
      rowHoverBg: '#F8FAFC',
      footerBg: 'transparent',
    },
    Tag: {
      borderRadiusSM: 6,
      defaultBg: '#F1F5F9',
      defaultColor: COLOR_TEXT_SECONDARY,
    },
    Tabs: {
      cardPadding: '8px 16px',
      horizontalMargin: '0 0 24px 0',
      itemActiveColor: BRAND_PRIMARY,
      itemSelectedColor: BRAND_PRIMARY,
      itemHoverColor: COLOR_TEXT,
      inkBarColor: BRAND_PRIMARY,
      titleFontSize: 14,
    },
    Form: {
      labelFontSize: 13,
      labelColor: COLOR_TEXT_SECONDARY,
      verticalLabelPadding: '0 0 6px',
      itemMarginBottom: 20,
    },
    Dropdown: {
      borderRadiusLG: 10,
      controlItemBgHover: '#F1F5F9',
      borderRadius: 10,
    },
    Tooltip: {
      borderRadius: 6,
      colorBgSpotlight: 'rgba(15, 23, 42, 0.92)',
    },
    Popconfirm: {
      borderRadiusLG: 12,
    },
    Switch: {
      handleBg: '#FFFFFF',
    },
    Upload: {
      borderRadiusLG: 10,
    },
    Drawer: {
      paddingLG: 24,
    },
    Alert: {
      borderRadiusLG: 10,
      paddingContentHorizontalLG: 16,
    },
    Typography: {
      titleMarginTop: 0,
      titleMarginBottom: 0,
    },
  },
}
