"""initial schema: 10 tables (5 业务 + 4 组织 + 1 期间锁定)

Revision ID: 0a3dea0e7527
Revises: 
Create Date: 2026-08-10 09:07:20.922515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a3dea0e7527'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_segments_name'), ['name'], unique=True)

    op.create_table('filling_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filling_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filling_periods_locked'), ['locked'], unique=False)
        batch_op.create_index(batch_op.f('ix_filling_periods_period'), ['period'], unique=True)

    op.create_table('function_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('function_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_function_tags_name'), ['name'], unique=True)

    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('row_label_cols', sa.Integer(), nullable=False),
    sa.Column('col_label_rows', sa.Integer(), nullable=False),
    sa.Column('content_rows', sa.Integer(), nullable=False),
    sa.Column('content_cols', sa.Integer(), nullable=False),
    sa.Column('content_numeric', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_year'), ['year'], unique=False)

    op.create_table('org_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['business_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_entities_segment_id'), ['segment_id'], unique=False)

    op.create_table('org_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['org_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_departments_entity_id'), ['entity_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('function_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['org_departments.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['org_entities.id'], ),
    sa.ForeignKeyConstraint(['function_tag_id'], ['function_tags.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['business_segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_function_tag_id'), ['function_tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_segment_id'), ['segment_id'], unique=False)

    op.create_table('role_template_mapping',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'template_id')
    )
    op.create_table('role_workbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submit_at', sa.DateTime(), nullable=True),
    sa.Column('review_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'template_id', 'period')
    )
    with op.batch_alter_table('role_workbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_workbooks_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_workbooks_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_workbooks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_workbooks_template_id'), ['template_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_is_default'))

    op.drop_table('users')
    with op.batch_alter_table('role_workbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_workbooks_template_id'))
        batch_op.drop_index(batch_op.f('ix_role_workbooks_status'))
        batch_op.drop_index(batch_op.f('ix_role_workbooks_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_workbooks_period'))

    op.drop_table('role_workbooks')
    op.drop_table('role_template_mapping')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_segment_id'))
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_function_tag_id'))
        batch_op.drop_index(batch_op.f('ix_roles_entity_id'))
        batch_op.drop_index(batch_op.f('ix_roles_department_id'))

    op.drop_table('roles')
    with op.batch_alter_table('org_departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_departments_entity_id'))

    op.drop_table('org_departments')
    with op.batch_alter_table('org_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_entities_segment_id'))

    op.drop_table('org_entities')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_year'))
        batch_op.drop_index(batch_op.f('ix_templates_name'))
        batch_op.drop_index(batch_op.f('ix_templates_archived'))

    op.drop_table('templates')
    with op.batch_alter_table('function_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_function_tags_name'))

    op.drop_table('function_tags')
    with op.batch_alter_table('filling_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filling_periods_period'))
        batch_op.drop_index(batch_op.f('ix_filling_periods_locked'))

    op.drop_table('filling_periods')
    with op.batch_alter_table('business_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_segments_name'))

    op.drop_table('business_segments')
    # ### end Alembic commands ###
