export const APP_NAME = '在线表格'
export const APP_SHORT_NAME = '在线表格'
export const APP_TAGLINE = 'RBAC · 模板化填报 · 审核流'
export const APP_VERSION = 'v2.0'
export const ADMIN_ROLE_NAME = '管理员'

export const BRAND_PRIMARY = '#2D5BFF'
export const BRAND_PRIMARY_HOVER = '#1E47E0'
export const BRAND_PRIMARY_ACTIVE = '#1739C7'
export const BRAND_PRIMARY_SOFT = '#EEF2FF'

export const COLOR_TEXT = '#0F172A'
export const COLOR_TEXT_SECONDARY = '#475569'
export const COLOR_TEXT_TERTIARY = '#94A3B8'
export const COLOR_BORDER = '#E5E7EB'
export const COLOR_BORDER_SUBTLE = '#F1F5F9'
export const COLOR_BG = '#F7F8FA'
export const COLOR_SURFACE = '#FFFFFF'

export const STATUS_DRAFT = '#2D5BFF'
export const STATUS_SUBMITTED = '#EA8C00'
export const STATUS_APPROVED = '#10B981'
export const STATUS_REJECTED = '#EF4444'
export const STATUS_NONE = '#94A3B8'
